package com.westtextile.persistence.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class Shops {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shops.shopid
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private Integer shopid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shops.shopname
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private String shopname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shops.shoptype
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private String shoptype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shops.shopsquare
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private BigDecimal shopsquare;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shops.shopamount
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private Integer shopamount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shops.buildnumber
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private Integer buildnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shops.floornumber
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private Integer floornumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shops.userid
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shops.note
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shops.indate
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private Date indate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shops.shopid
	 * @return  the value of shops.shopid
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public Integer getShopid() {
		return shopid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shops.shopid
	 * @param shopid  the value for shops.shopid
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setShopid(Integer shopid) {
		this.shopid = shopid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shops.shopname
	 * @return  the value of shops.shopname
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public String getShopname() {
		return shopname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shops.shopname
	 * @param shopname  the value for shops.shopname
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setShopname(String shopname) {
		this.shopname = shopname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shops.shoptype
	 * @return  the value of shops.shoptype
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public String getShoptype() {
		return shoptype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shops.shoptype
	 * @param shoptype  the value for shops.shoptype
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setShoptype(String shoptype) {
		this.shoptype = shoptype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shops.shopsquare
	 * @return  the value of shops.shopsquare
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public BigDecimal getShopsquare() {
		return shopsquare;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shops.shopsquare
	 * @param shopsquare  the value for shops.shopsquare
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setShopsquare(BigDecimal shopsquare) {
		this.shopsquare = shopsquare;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shops.shopamount
	 * @return  the value of shops.shopamount
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public Integer getShopamount() {
		return shopamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shops.shopamount
	 * @param shopamount  the value for shops.shopamount
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setShopamount(Integer shopamount) {
		this.shopamount = shopamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shops.buildnumber
	 * @return  the value of shops.buildnumber
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public Integer getBuildnumber() {
		return buildnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shops.buildnumber
	 * @param buildnumber  the value for shops.buildnumber
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setBuildnumber(Integer buildnumber) {
		this.buildnumber = buildnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shops.floornumber
	 * @return  the value of shops.floornumber
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public Integer getFloornumber() {
		return floornumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shops.floornumber
	 * @param floornumber  the value for shops.floornumber
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setFloornumber(Integer floornumber) {
		this.floornumber = floornumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shops.userid
	 * @return  the value of shops.userid
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shops.userid
	 * @param userid  the value for shops.userid
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shops.note
	 * @return  the value of shops.note
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shops.note
	 * @param note  the value for shops.note
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shops.indate
	 * @return  the value of shops.indate
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public Date getIndate() {
		return indate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shops.indate
	 * @param indate  the value for shops.indate
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setIndate(Date indate) {
		this.indate = indate;
	}
}