package com.westtextile.persistence.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class Shops {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shop_id
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    private Integer shop_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shop_name
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    private String shop_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shop_type
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    private String shop_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shop_square
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    private BigDecimal shop_square;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shop_price
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    private Integer shop_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.build_number
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    private Integer build_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.floor_number
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    private Integer floor_number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.user_id
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.buy_date
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    private Date buy_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.note
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.indate
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    private Date indate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shop_id
     *
     * @return the value of shops.shop_id
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shop_id
     *
     * @param shop_id the value for shops.shop_id
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shop_name
     *
     * @return the value of shops.shop_name
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public String getShop_name() {
        return shop_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shop_name
     *
     * @param shop_name the value for shops.shop_name
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public void setShop_name(String shop_name) {
        this.shop_name = shop_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shop_type
     *
     * @return the value of shops.shop_type
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public String getShop_type() {
        return shop_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shop_type
     *
     * @param shop_type the value for shops.shop_type
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public void setShop_type(String shop_type) {
        this.shop_type = shop_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shop_square
     *
     * @return the value of shops.shop_square
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public BigDecimal getShop_square() {
        return shop_square;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shop_square
     *
     * @param shop_square the value for shops.shop_square
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public void setShop_square(BigDecimal shop_square) {
        this.shop_square = shop_square;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shop_price
     *
     * @return the value of shops.shop_price
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public Integer getShop_price() {
        return shop_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shop_price
     *
     * @param shop_price the value for shops.shop_price
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public void setShop_price(Integer shop_price) {
        this.shop_price = shop_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.build_number
     *
     * @return the value of shops.build_number
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public Integer getBuild_number() {
        return build_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.build_number
     *
     * @param build_number the value for shops.build_number
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public void setBuild_number(Integer build_number) {
        this.build_number = build_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.floor_number
     *
     * @return the value of shops.floor_number
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public Integer getFloor_number() {
        return floor_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.floor_number
     *
     * @param floor_number the value for shops.floor_number
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public void setFloor_number(Integer floor_number) {
        this.floor_number = floor_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.user_id
     *
     * @return the value of shops.user_id
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.user_id
     *
     * @param user_id the value for shops.user_id
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.buy_date
     *
     * @return the value of shops.buy_date
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public Date getBuy_date() {
        return buy_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.buy_date
     *
     * @param buy_date the value for shops.buy_date
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public void setBuy_date(Date buy_date) {
        this.buy_date = buy_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.note
     *
     * @return the value of shops.note
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.note
     *
     * @param note the value for shops.note
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.indate
     *
     * @return the value of shops.indate
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public Date getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.indate
     *
     * @param indate the value for shops.indate
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public void setIndate(Date indate) {
        this.indate = indate;
    }
}