package com.westtextile.persistence.mybatis.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.userid
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.isadmin
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	private Boolean isadmin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.isvalidate
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	private Boolean isvalidate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.displayname
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	private String displayname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.qqnumber
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	private Integer qqnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.career
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	private String career;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.sex
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.age
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.identityid
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	private String identityid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.indate
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	private Date indate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.note
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.userid
	 * @return  the value of user.userid
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.userid
	 * @param userid  the value for user.userid
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.isadmin
	 * @return  the value of user.isadmin
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public Boolean getIsadmin() {
		return isadmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.isadmin
	 * @param isadmin  the value for user.isadmin
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public void setIsadmin(Boolean isadmin) {
		this.isadmin = isadmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.isvalidate
	 * @return  the value of user.isvalidate
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public Boolean getIsvalidate() {
		return isvalidate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.isvalidate
	 * @param isvalidate  the value for user.isvalidate
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public void setIsvalidate(Boolean isvalidate) {
		this.isvalidate = isvalidate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.displayname
	 * @return  the value of user.displayname
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public String getDisplayname() {
		return displayname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.displayname
	 * @param displayname  the value for user.displayname
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public void setDisplayname(String displayname) {
		this.displayname = displayname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.qqnumber
	 * @return  the value of user.qqnumber
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public Integer getQqnumber() {
		return qqnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.qqnumber
	 * @param qqnumber  the value for user.qqnumber
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public void setQqnumber(Integer qqnumber) {
		this.qqnumber = qqnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.career
	 * @return  the value of user.career
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public String getCareer() {
		return career;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.career
	 * @param career  the value for user.career
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public void setCareer(String career) {
		this.career = career;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.sex
	 * @return  the value of user.sex
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.sex
	 * @param sex  the value for user.sex
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.age
	 * @return  the value of user.age
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.age
	 * @param age  the value for user.age
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.identityid
	 * @return  the value of user.identityid
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public String getIdentityid() {
		return identityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.identityid
	 * @param identityid  the value for user.identityid
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public void setIdentityid(String identityid) {
		this.identityid = identityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.indate
	 * @return  the value of user.indate
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public Date getIndate() {
		return indate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.indate
	 * @param indate  the value for user.indate
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public void setIndate(Date indate) {
		this.indate = indate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.note
	 * @return  the value of user.note
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.note
	 * @param note  the value for user.note
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	public void setNote(String note) {
		this.note = note;
	}
}