package com.westtextile.persistence.mybatis.model;

public class UserWithBLOBs extends User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    private byte[] password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.identity_id
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    private byte[] identity_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public byte[] getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public void setPassword(byte[] password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.identity_id
     *
     * @return the value of user.identity_id
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public byte[] getIdentity_id() {
        return identity_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.identity_id
     *
     * @param identity_id the value for user.identity_id
     *
     * @mbggenerated Wed Feb 11 17:02:08 CST 2015
     */
    public void setIdentity_id(byte[] identity_id) {
        this.identity_id = identity_id;
    }
}