package com.westtextile.persistence.mybatis.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.userid
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.displayname
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private String displayname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.qqnumber
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private Integer qqnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.career
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private String career;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.age
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.indate
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private Date indate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.note
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.userid
	 * @return  the value of user.userid
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.userid
	 * @param userid  the value for user.userid
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.displayname
	 * @return  the value of user.displayname
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public String getDisplayname() {
		return displayname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.displayname
	 * @param displayname  the value for user.displayname
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setDisplayname(String displayname) {
		this.displayname = displayname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.qqnumber
	 * @return  the value of user.qqnumber
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public Integer getQqnumber() {
		return qqnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.qqnumber
	 * @param qqnumber  the value for user.qqnumber
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setQqnumber(Integer qqnumber) {
		this.qqnumber = qqnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.career
	 * @return  the value of user.career
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public String getCareer() {
		return career;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.career
	 * @param career  the value for user.career
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setCareer(String career) {
		this.career = career;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.age
	 * @return  the value of user.age
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.age
	 * @param age  the value for user.age
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.indate
	 * @return  the value of user.indate
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public Date getIndate() {
		return indate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.indate
	 * @param indate  the value for user.indate
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setIndate(Date indate) {
		this.indate = indate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.note
	 * @return  the value of user.note
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.note
	 * @param note  the value for user.note
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setNote(String note) {
		this.note = note;
	}
}