package com.westtextile.persistence.mybatis.model;

public class UserWithBLOBs extends User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private byte[] password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.identityid
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	private byte[] identityid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public byte[] getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setPassword(byte[] password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.identityid
	 * @return  the value of user.identityid
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public byte[] getIdentityid() {
		return identityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.identityid
	 * @param identityid  the value for user.identityid
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	public void setIdentityid(byte[] identityid) {
		this.identityid = identityid;
	}
}