package com.westtextile.persistence.mybatis.model;

public class UserWithBLOBs extends User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Mon Feb 16 11:26:29 CST 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.identityid
	 * @mbggenerated  Mon Feb 16 11:26:29 CST 2015
	 */
	private String identityid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Mon Feb 16 11:26:29 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Mon Feb 16 11:26:29 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.identityid
	 * @return  the value of user.identityid
	 * @mbggenerated  Mon Feb 16 11:26:29 CST 2015
	 */
	public String getIdentityid() {
		return identityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.identityid
	 * @param identityid  the value for user.identityid
	 * @mbggenerated  Mon Feb 16 11:26:29 CST 2015
	 */
	public void setIdentityid(String identityid) {
		this.identityid = identityid;
	}
}