package com.westtextile.persistence.mybatis.client;

import java.util.List;

import com.westtextile.persistence.mybatis.model.Shops;

public interface ShopsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shops
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer shopid);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shops
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	int insert(Shops record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shops
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	int insertSelective(Shops record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shops
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	Shops selectByPrimaryKey(Integer shopid);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shops
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	int updateByPrimaryKeySelective(Shops record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shops
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	int updateByPrimaryKey(Shops record);
	Shops selectByShopName(String shopname);
	List<Shops> selectByUserName(String username);

	int deleteByShopName(String shopname);
	int deleteByUserName(String username);
}