package com.westtextile.persistence.mybatis.client;

import com.westtextile.persistence.mybatis.model.User;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer userid);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	int insert(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	int insertSelective(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	User selectByPrimaryKey(Integer userid);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	int updateByPrimaryKeySelective(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Feb 28 17:02:39 CST 2015
	 */
	int updateByPrimaryKey(User record);
	User selectByUserName(String username);
	int updateByUserNameWithBLOBs(User record);
}