package com.westtextile.persistence.mybatis.client;

import org.apache.ibatis.annotations.Insert;

import com.westtextile.persistence.mybatis.model.User;
import com.westtextile.persistence.mybatis.model.UserWithBLOBs;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	int deleteByPrimaryKey(Integer userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	@Insert("    insert into user (userid, username, displayname, "+
      "qqnumber, career, age, "+
      "indate, note, password,"+ 
      "identityid)"+
    "values (#{userid,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, #{displayname,jdbcType=VARCHAR},"+ 
      "#{qqnumber,jdbcType=INTEGER}, #{career,jdbcType=VARCHAR}, #{age,jdbcType=INTEGER}, "+
      "#{indate,jdbcType=TIMESTAMP}, #{note,jdbcType=VARCHAR}, #{password,jdbcType=VARBINARY},"+ 
      "#{identityid,jdbcType=VARBINARY})")
	int insert(UserWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	int insertSelective(UserWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	UserWithBLOBs selectByPrimaryKey(Integer userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	int updateByPrimaryKeySelective(UserWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(UserWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Sat Feb 14 16:45:31 CST 2015
	 */
	int updateByPrimaryKey(User record);
}